from enum import StrEnum

class ExecutionPhase(StrEnum):
    PLAN_BOUND = "PLAN_BOUND"
    AUTHORIZED = "AUTHORIZED"
    PRECONDITIONS_VERIFIED = "PRECONDITIONS_VERIFIED"
    FINAL_POINT_APPLIED = "FINAL_POINT_APPLIED"
    SOURCE_REANALYZED = "SOURCE_REANALYZED"
    SOURCE_COMPLETE = "SOURCE_COMPLETE"
    ASYNC_APPLIED = "ASYNC_APPLIED"
    SOURCE_REMOVED = "SOURCE_REMOVED"
    CANONICAL_SOURCE_COMPLETE = "CANONICAL_SOURCE_COMPLETE"
    GLOBAL_VALIDATION = "GLOBAL_VALIDATION"
    PROMOTION_READY = "PROMOTION_READY"
    PROMOTED = "PROMOTED"
    POST_PROMOTION_VERIFIED = "POST_PROMOTION_VERIFIED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
