from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Protocol

SOURCE_LANGUAGE = "en"
GENERATED_COMMENT = (
    "<!-- AUTO-GENERATED: README.md is canonical. "
    "Generated by self-hosted Argos Translate; do not edit directly. -->"
)
LANGUAGE_METADATA = {
    "ko": {
        "label": "한국어",
        "notice": (
            "> 이 문서는 정식 원본인 [`README.md`](README.md)를 기준으로 "
            "self-hosted Argos Translate가 생성하는 한국어 번역본입니다. "
            "프로젝트 사실이나 의미가 상충할 경우 영문 원본을 기준으로 합니다."
        ),
    },
}
NORMATIVE = ("MUST NOT", "SHOULD NOT", "MUST", "SHOULD", "MAY")
PROPER_TERMS = (
    "Primary Lifecycle Ownership and Responsibility Isolation Policy",
    "Product SDK Plane",
    "Toolchain SDK Plane",
    "Consumer Repository",
    "Reference Tool",
    "Enforced Conformance",
    "Responsibility Map",
    "Project Profile",
    "Product Artifact",
    "Specification",
    "PTSIP",
    "VPMS",
    "Pilot",
    "Tool",
)
INLINE = re.compile(
    r"(`+[^`\n]*`+)"
    r"|(\[[^\]\n]+\]\([^)]+\))"
    r"|(<[^>\n]+>)"
    r"|(https?://[^\s<>)]+)"
    r"|(\b[0-9a-f]{40,64}\b)"
    r"|(\bv?\d+\.\d+(?:\.\d+)?(?:-[A-Za-z0-9.]+)?\b)"
    r"|(\*\*|__|~~|\*)"
    r"|\b(" + "|".join(re.escape(x) for x in (*NORMATIVE, *PROPER_TERMS)) + r")\b"
)
LINK = re.compile(r"^\[([^\]\n]+)\]\(([^)]+)\)$")
FENCE = re.compile(r"^\s*(```+|~~~+)")
TABLE_DIVIDER = re.compile(r"^\s*:?-{3,}:?\s*$")


class Translator(Protocol):
    def translate(self, text: str) -> str: ...


class ArgosTranslator:
    def __init__(self, source: str, target: str) -> None:
        import argostranslate.package as package
        import argostranslate.translate as translate
        from packaging.version import Version

        installed = package.get_installed_packages()
        direct = any(
            pkg.type == "translate"
            and pkg.from_code == source
            and pkg.to_code == target
            for pkg in installed
        )
        if not direct:
            print(f"Installing Argos model {source}->{target}.")
            package.update_package_index()
            available = [
                pkg
                for pkg in package.get_available_packages()
                if pkg.type == "translate"
                and pkg.from_code == source
                and pkg.to_code == target
            ]
            if not available:
                raise RuntimeError(
                    f"No Argos Translate model is available for {source}->{target}."
                )
            selected = max(
                available,
                key=lambda pkg: Version(pkg.package_version or "0"),
            )
            package.install_from_path(selected.download())
            print(
                f"Installed Argos model {source}->{target} "
                f"{selected.package_version or 'unknown'}."
            )

        loaded = translate.get_translation_from_codes(source, target)
        if loaded is None:
            raise RuntimeError(f"Unable to load Argos translation {source}->{target}.")
        self._translation = loaded

    def translate(self, text: str) -> str:
        result = self._translation.translate(text)
        if not isinstance(result, str) or not result.strip():
            raise RuntimeError("Argos Translate returned an empty segment.")
        return result


def strip_navigation(source: str) -> str:
    return re.sub(
        r'\A\s*<p\s+align=["\']right["\']>.*?</p>\s*',
        "",
        source,
        count=1,
        flags=re.DOTALL | re.IGNORECASE,
    )


def translate_plain(text: str, translator: Translator) -> str:
    return translator.translate(text) if re.search(r"[A-Za-z]", text) else text


def translate_inline(text: str, translator: Translator) -> str:
    out: list[str] = []
    cursor = 0
    for match in INLINE.finditer(text):
        if match.start() > cursor:
            out.append(translate_plain(text[cursor : match.start()], translator))
        token = match.group(0)
        link = LINK.match(token)
        if link:
            label, target = link.groups()
            out.append(f"[{translate_inline(label, translator)}]({target})")
        else:
            out.append(token)
        cursor = match.end()
    if cursor < len(text):
        out.append(translate_plain(text[cursor:], translator))
    return "".join(out)


def translate_table(line: str, translator: Translator) -> str:
    cells = line.split("|")
    cores = [cell.strip() for cell in cells[1:-1]]
    if cores and all(TABLE_DIVIDER.fullmatch(core) for core in cores):
        return line

    out: list[str] = []
    for cell in cells:
        leading = cell[: len(cell) - len(cell.lstrip())]
        trailing = cell[len(cell.rstrip()) :]
        core = cell.strip()
        if core:
            core = translate_inline(core, translator)
        out.append(f"{leading}{core}{trailing}")
    return "|".join(out)


def translate_markdown(source: str, translator: Translator) -> str:
    output: list[str] = []
    in_fence = False
    fence_char = ""
    first_h1 = True

    for line in source.splitlines():
        fence = FENCE.match(line)
        if fence:
            marker = fence.group(1)[0]
            if not in_fence:
                in_fence = True
                fence_char = marker
            elif marker == fence_char:
                in_fence = False
                fence_char = ""
            output.append(line)
            continue

        if in_fence or not line.strip():
            output.append(line)
            continue

        if line.startswith("# ") and first_h1:
            output.append(line)
            first_h1 = False
            continue

        heading = re.match(r"^(#{1,6}\s+)(.*)$", line)
        if heading:
            output.append(heading.group(1) + translate_inline(heading.group(2), translator))
            continue

        quote = re.match(r"^(>\s*)(.*)$", line)
        if quote:
            output.append(quote.group(1) + translate_inline(quote.group(2), translator))
            continue

        item = re.match(r"^(\s*(?:[-+*]|\d+[.)])\s+)(.*)$", line)
        if item:
            output.append(item.group(1) + translate_inline(item.group(2), translator))
            continue

        if line.strip().startswith("|") and line.strip().endswith("|"):
            output.append(translate_table(line, translator))
            continue

        if line.lstrip().startswith("<") and line.rstrip().endswith(">"):
            output.append(line)
            continue

        output.append(translate_inline(line, translator))

    return "\n".join(output).rstrip() + "\n"


def render(source: str, target: str, translator: Translator) -> str:
    metadata = LANGUAGE_METADATA.get(target)
    if metadata is None:
        raise RuntimeError(f"Unsupported localized README language: {target}")

    translated = translate_markdown(strip_navigation(source), translator)
    lines = translated.splitlines()
    if not lines or not lines[0].startswith("# "):
        raise RuntimeError("README.md must contain a top-level '# ' title.")
    title = lines[0]
    body = "\n".join(lines[1:]).lstrip("\n").rstrip()

    nav = (
        '<p align="right">\n'
        '  <a href="README.md">English</a> | '
        f'{metadata["label"]}\n'
        "</p>"
    )
    return (
        f"{GENERATED_COMMENT}\n{nav}\n\n{title}\n\n"
        f"{metadata['notice']}\n\n{body}\n"
    )


def fenced_blocks(text: str) -> list[str]:
    return re.findall(r"(?ms)^```[^\n]*\n.*?^```[ \t]*$", text)


def heading_levels(text: str) -> list[int]:
    return [len(m.group(1)) for m in re.finditer(r"(?m)^(#{1,6})\s+", text)]


def link_targets(text: str) -> list[str]:
    return [x.strip().split(" ", 1)[0] for x in re.findall(r"\]\(([^)]+)\)", text)]


def inline_code(text: str) -> list[str]:
    return re.findall(r"`+[^`\n]*`+", text)


def validate(source: str, localized: str, target: str) -> None:
    canonical = strip_navigation(source)
    if target == "ko" and not re.search(r"[가-힣]", localized):
        raise RuntimeError("Translation validation failed: Korean text is missing.")
    if heading_levels(canonical) != heading_levels(localized):
        raise RuntimeError("Translation validation failed: heading structure changed.")
    if fenced_blocks(canonical) != fenced_blocks(localized):
        raise RuntimeError("Translation validation failed: fenced code blocks changed.")

    missing_links = [x for x in link_targets(canonical) if x not in localized]
    if missing_links:
        raise RuntimeError(
            "Translation validation failed: link targets disappeared: "
            + ", ".join(sorted(set(missing_links)))
        )

    missing_code = [x for x in inline_code(canonical) if x not in localized]
    if missing_code:
        raise RuntimeError(
            "Translation validation failed: inline code changed: "
            + ", ".join(sorted(set(missing_code))[:20])
        )

    for keyword in NORMATIVE:
        if re.search(rf"\b{re.escape(keyword)}\b", canonical) and keyword not in localized:
            raise RuntimeError(
                f"Translation validation failed: normative keyword {keyword!r} disappeared."
            )


def parse_target(value: str) -> tuple[str, Path]:
    if ":" not in value:
        raise argparse.ArgumentTypeError("target must use <language-code>:<path>")
    code, raw_path = value.split(":", 1)
    if not code.strip() or not raw_path.strip():
        raise argparse.ArgumentTypeError("target must use <language-code>:<path>")
    return code.strip(), Path(raw_path.strip())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("README.md"))
    parser.add_argument("--target", action="append", type=parse_target, required=True)
    args = parser.parse_args()

    source = args.source.read_text(encoding="utf-8").lstrip("\ufeff")
    for target_code, target_path in args.target:
        translator = ArgosTranslator(SOURCE_LANGUAGE, target_code)
        localized = render(source, target_code, translator)
        validate(source, localized, target_code)

        current = (
            target_path.read_text(encoding="utf-8") if target_path.exists() else None
        )
        if current == localized:
            print(f"{target_path} is already synchronized.")
            continue
        target_path.write_text(localized, encoding="utf-8", newline="\n")
        print(f"Updated {target_path} with local Argos Translate.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
