from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

API_URL = "https://models.github.ai/inference/chat/completions"
DEFAULT_MODEL = "openai/gpt-4o"
SOURCE_PATH = Path("README.md")
TARGET_PATH = Path("README.ko.md")

GENERATED_COMMENT = (
    "<!-- AUTO-GENERATED: README.md is the canonical source. "
    "Do not edit this file directly. -->"
)
KOREAN_NAV = '<p align="right">\n  <a href="README.md">English</a> | 한국어\n</p>'
KOREAN_NOTICE = (
    "> 이 문서는 정식 원본인 [`README.md`](README.md)를 기준으로 자동 생성되는 "
    "한국어 번역본입니다. 프로젝트 사실이나 의미가 상충할 경우 영문 원본을 기준으로 합니다."
)


def _read_source() -> str:
    if not SOURCE_PATH.is_file():
        raise RuntimeError(f"Missing canonical README: {SOURCE_PATH}")
    return SOURCE_PATH.read_text(encoding="utf-8").lstrip("\ufeff")


def _split_source(source: str) -> tuple[str, str]:
    source = re.sub(
        r'\A\s*<p\s+align=["\']right["\']>.*?</p>\s*',
        "",
        source,
        count=1,
        flags=re.DOTALL | re.IGNORECASE,
    )
    match = re.search(r"(?m)^#\s+.+$", source)
    if not match:
        raise RuntimeError("README.md must contain a top-level '# ' title.")
    title = match.group(0).strip()
    body = source[match.end() :].lstrip("\r\n")
    return title, body


def _prompt(body: str) -> list[dict[str, str]]:
    system = (
        "You are a documentation localization engine. Translate the supplied Markdown from English "
        "to natural Korean while preserving technical meaning exactly. Return only the translated "
        "Markdown body, with no commentary and no enclosing Markdown fence."
    )
    user = f"""Translate the following canonical README body to Korean.

Rules:
1. Preserve Markdown structure, heading levels, lists, tables, blockquotes, emphasis, and link destinations.
2. Preserve every fenced code block EXACTLY, including its language marker, comments, commands, spacing, and versions.
3. Preserve URLs, repository paths, package names, CLI commands, environment variables, hashes, schema IDs, tag namespaces, and code identifiers exactly.
4. Preserve the normative keywords MUST, MUST NOT, SHOULD, SHOULD NOT, and MAY in uppercase English.
5. Keep PTSIP-specific proper nouns such as Product SDK Plane, Toolchain SDK Plane, Consumer Repository, Reference Tool, Specification, Tool, Pilot, and Enforced Conformance in English when translating them would reduce precision. Korean explanatory text around them is preferred.
6. Do not invent, remove, summarize, reorder, or update facts. Translate the full body one-to-one.
7. Do not add a language selector, H1 title, auto-generation notice, or translator note; the generator adds those separately.

--- SOURCE BODY START ---
{body}
--- SOURCE BODY END ---
"""
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def _request_translation(token: str, model: str, body: str) -> str:
    payload = json.dumps(
        {
            "model": model,
            "messages": _prompt(body),
            "temperature": 0.1,
            "max_tokens": 12000,
        }
    ).encode("utf-8")

    request = urllib.request.Request(
        API_URL,
        data=payload,
        headers={
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    last_error: Exception | None = None
    for attempt in range(3):
        try:
            with urllib.request.urlopen(request, timeout=120) as response:
                data = json.load(response)
            content = data["choices"][0]["message"]["content"]
            if not isinstance(content, str) or not content.strip():
                raise RuntimeError("GitHub Models returned an empty translation.")
            return content.strip()
        except urllib.error.HTTPError as exc:
            body_text = exc.read().decode("utf-8", errors="replace")[:1000]
            last_error = RuntimeError(
                f"GitHub Models HTTP {exc.code}: {body_text or exc.reason}"
            )
            if exc.code != 429 and exc.code < 500:
                raise last_error from exc
        except (urllib.error.URLError, TimeoutError, KeyError, IndexError, TypeError) as exc:
            last_error = exc

        if attempt < 2:
            time.sleep(2 ** (attempt + 1))

    raise RuntimeError(f"GitHub Models request failed after retries: {last_error}")


def _clean_model_output(text: str) -> str:
    text = text.strip().replace("\r\n", "\n")
    lines = text.splitlines()

    if (
        len(lines) >= 2
        and lines[0].strip().lower() in {"```markdown", "```md"}
        and lines[-1].strip() == "```"
    ):
        text = "\n".join(lines[1:-1]).strip()
        lines = text.splitlines()

    if lines and re.match(r"^#\s+", lines[0]):
        text = "\n".join(lines[1:]).lstrip("\n")

    return text.rstrip()


def _fenced_blocks(text: str) -> list[str]:
    return re.findall(r"(?ms)^```[^\n]*\n.*?^```[ \t]*$", text)


def _heading_levels(text: str) -> list[int]:
    return [len(match.group(1)) for match in re.finditer(r"(?m)^(#{2,6})\s+", text)]


def _link_targets(text: str) -> list[str]:
    targets: list[str] = []
    for raw in re.findall(r"\]\(([^)]+)\)", text):
        target = raw.strip()
        if target.startswith("<") and target.endswith(">"):
            target = target[1:-1]
        elif " " in target:
            target = target.split(" ", 1)[0]
        targets.append(target)
    return targets


def _validate_translation(source_body: str, translated_body: str) -> None:
    if not re.search(r"[가-힣]", translated_body):
        raise RuntimeError("Translation validation failed: no Korean text was found.")

    source_headings = _heading_levels(source_body)
    translated_headings = _heading_levels(translated_body)
    if source_headings != translated_headings:
        raise RuntimeError(
            "Translation validation failed: Markdown heading structure changed "
            f"({source_headings} != {translated_headings})."
        )

    if _fenced_blocks(source_body) != _fenced_blocks(translated_body):
        raise RuntimeError(
            "Translation validation failed: one or more fenced code blocks changed."
        )

    missing_targets = [
        target for target in _link_targets(source_body) if target not in translated_body
    ]
    if missing_targets:
        raise RuntimeError(
            "Translation validation failed: link destinations changed or disappeared: "
            + ", ".join(sorted(set(missing_targets)))
        )

    for keyword in ("MUST", "MUST NOT", "SHOULD", "SHOULD NOT", "MAY"):
        if keyword in source_body and keyword not in translated_body:
            raise RuntimeError(
                f"Translation validation failed: normative keyword {keyword!r} disappeared."
            )

    ratio = len(translated_body) / max(len(source_body), 1)
    if ratio < 0.35 or ratio > 2.0:
        raise RuntimeError(
            f"Translation validation failed: suspicious output length ratio {ratio:.2f}."
        )


def _render(title: str, translated_body: str) -> str:
    return (
        f"{GENERATED_COMMENT}\n"
        f"{KOREAN_NAV}\n\n"
        f"{title}\n\n"
        f"{KOREAN_NOTICE}\n\n"
        f"{translated_body.rstrip()}\n"
    )


def main() -> int:
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if not token:
        print("GITHUB_TOKEN or GH_TOKEN is required.", file=sys.stderr)
        return 2

    model = os.environ.get("GITHUB_MODELS_MODEL", DEFAULT_MODEL).strip() or DEFAULT_MODEL
    source = _read_source()
    title, source_body = _split_source(source)

    translated = _clean_model_output(_request_translation(token, model, source_body))
    _validate_translation(source_body, translated)
    rendered = _render(title, translated)

    current = TARGET_PATH.read_text(encoding="utf-8") if TARGET_PATH.exists() else None
    if current == rendered:
        print(f"{TARGET_PATH} is already synchronized.")
        return 0

    with TARGET_PATH.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print(f"Updated {TARGET_PATH} using {model}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
