"""Authority-aware generic remediation contracts."""

from .domain import (
    AuthorizationDecision,
    CoverageGap,
    DerivedFact,
    EscalationProof,
    MutationClass,
    NormativeConstraint,
    PostconditionResult,
    ProjectIntentAuthority,
    ProjectIntentSource,
    RemediationContext,
    RemediationContractError,
    RemediationDisposition,
    RemediationDispositionCandidate,
    RepositoryChangePlan,
    ResolutionOutcome,
    SemanticCandidate,
    SemanticRemediationPlan,
)

__all__ = [
    "AuthorizationDecision",
    "CoverageGap",
    "DerivedFact",
    "EscalationProof",
    "MutationClass",
    "NormativeConstraint",
    "PostconditionResult",
    "ProjectIntentAuthority",
    "ProjectIntentSource",
    "RemediationContext",
    "RemediationContractError",
    "RemediationDisposition",
    "RemediationDispositionCandidate",
    "RepositoryChangePlan",
    "ResolutionOutcome",
    "SemanticCandidate",
    "SemanticRemediationPlan",
]
