"""Authority-aware generic remediation contracts."""

from .domain import (
    AuthorizationDecision,
    CoverageGap,
    DerivedFact,
    EscalationProof,
    MutationClass,
    NormativeConstraint,
    PostconditionResult,
    ProjectIntentAuthority,
    ProjectIntentSource,
    RemediationContext,
    RemediationContractError,
    RemediationDisposition,
    RemediationDispositionCandidate,
    RepositoryChangePlan,
    ResolutionOutcome,
    SemanticCandidate,
    SemanticRemediationPlan,
)
from .rules import (
    OperationalRule,
    OperationalRuleBinding,
    OperationalRuleCapabilityDeclaration,
    OperationalRuleContractError,
    OperationalRuleEvaluation,
    RuleAutomationLevel,
    RuleCapabilityState,
    RuleEvaluationStatus,
    RuleRequirementKind,
)

__all__ = [
    "AuthorizationDecision",
    "CoverageGap",
    "DerivedFact",
    "EscalationProof",
    "MutationClass",
    "NormativeConstraint",
    "OperationalRule",
    "OperationalRuleBinding",
    "OperationalRuleCapabilityDeclaration",
    "OperationalRuleContractError",
    "OperationalRuleEvaluation",
    "PostconditionResult",
    "ProjectIntentAuthority",
    "ProjectIntentSource",
    "RemediationContext",
    "RemediationContractError",
    "RemediationDisposition",
    "RemediationDispositionCandidate",
    "RepositoryChangePlan",
    "ResolutionOutcome",
    "RuleAutomationLevel",
    "RuleCapabilityState",
    "RuleEvaluationStatus",
    "RuleRequirementKind",
    "SemanticCandidate",
    "SemanticRemediationPlan",
]
